[package]
name = "s2n-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
s2n-quic = "1.71.0"
socket2 = "0.6.1"
tokio = { version = "1.48.0", features = ["full"] }
